"""Hermetic tests for the todo ledger and the board projection."""

from __future__ import annotations

import json

import pytest

from papaya_agent_runtime import board, memory
from papaya_agent_runtime.cli import main
from papaya_agent_runtime.state import init_db, store


@pytest.fixture
def ppy_home(tmp_path, monkeypatch):
    monkeypatch.setenv("PPY_HOME", str(tmp_path / ".ppy"))
    return tmp_path / ".ppy"


def _run_with_task(conn, *, status="in_progress"):
    repo_id = store.add_repo(
        conn, name="demo", origin="/o", local_path="/l", default_branch="main", base_sha="a"
    )
    run_id = store.create_run(conn, "ship it")
    task_id = store.add_task(conn, run_id=run_id, title="build", repo_id=repo_id)
    store.update_task_fields(conn, task_id, provider="claude")
    store.set_task_status(conn, task_id, status)
    return run_id, task_id


def test_add_done_block_and_order(ppy_home) -> None:
    conn = init_db()
    run_id, task_id = _run_with_task(conn)
    a = board.add("review task 1's diff", run_id=run_id, task_id=task_id, conn=conn)
    b = board.add("ask user about the endpoint", blocked_on="user:endpoint", conn=conn)
    c = board.add("dispatch docs follow-up", conn=conn)

    assert [t["id"] for t in board.next_steps(conn)] == [a, c]
    assert [t["id"] for t in board.waiting(conn)] == [b]

    board.done(a, conn=conn)
    board.unblock(b, conn=conn)
    board.block(c, f"task:{task_id}", conn=conn)
    assert [t["id"] for t in board.next_steps(conn)] == [b]
    assert [t["id"] for t in board.waiting(conn)] == [c]
    assert [t["id"] for t in board.recently_done(conn)] == [a]

    board.reopen(a, conn=conn)
    assert [t["id"] for t in board.next_steps(conn)] == [a, b]
    board.drop(a, conn=conn)
    assert [t["id"] for t in board.next_steps(conn)] == [b]


def test_validation(ppy_home) -> None:
    conn = init_db()
    with pytest.raises(board.TodoError):
        board.add("   ", conn=conn)
    with pytest.raises(board.TodoError):
        board.add("x", run_id=99, conn=conn)
    with pytest.raises(board.TodoError):
        board.add("x", blocked_on="weather", conn=conn)
    with pytest.raises(board.TodoError):
        board.add("x", blocked_on="task:abc", conn=conn)
    with pytest.raises(board.TodoError):
        board.done(42, conn=conn)


def test_board_is_a_projection_rewritten_on_every_change(ppy_home) -> None:
    conn = init_db()
    run_id, task_id = _run_with_task(conn)
    memory.ensure_memory_layout()
    assert "Generated by `ppy board`" in memory.board_path().read_text()

    todo_id = board.add("review and deliver", run_id=run_id, conn=conn)
    text = memory.board_path().read_text()
    assert f'task {task_id} "build" (demo) [claude] — in_progress · no plan posted yet' in text
    assert f"[#{todo_id}] review and deliver (run {run_id})" in text
    assert "## Next" in text

    store.append_event(
        conn,
        kind="worker_progress",
        payload={"task_id": task_id, "phase": "plan", "note": "add module"},
        run_id=run_id,
        task_id=task_id,
    )
    board.done(todo_id, conn=conn)
    text = memory.board_path().read_text()
    assert "phase: plan" in text
    assert f"## Done (recent)\n- [#{todo_id}] review and deliver" in text
    assert "(no next steps recorded" in text


def test_cli_todo_board_and_status(ppy_home, capsys) -> None:
    conn = init_db()
    run_id, task_id = _run_with_task(conn)

    assert main(["todo", "add", "review task 1", "--run", str(run_id)]) == 0
    assert main(["todo", "add", "confirm endpoint", "--blocked-on", "user"]) == 0
    capsys.readouterr()
    assert main(["todo", "list"]) == 0
    out = capsys.readouterr().out
    assert "[ ] [#1] review task 1 (run 1)" in out
    assert "[ ] [#2] confirm endpoint — waiting on user" in out

    assert main(["todo", "done", "1"]) == 0
    assert main(["todo", "list", "--all", "--json"]) == 0
    rows = json.loads(capsys.readouterr().out.split("done: #1\n", 1)[1])
    assert {r["id"]: r["status"] for r in rows} == {1: "done", 2: "open"}

    assert main(["todo", "add", "x", "--blocked-on", "nope"]) == 1
    assert "blocked-on must be one of" in capsys.readouterr().err

    assert main(["board"]) == 0
    assert "# Work board (manager)" in capsys.readouterr().out

    assert main(["status"]) == 0
    out = capsys.readouterr().out
    assert "tasks:   1 in flight, 0 waiting on me" in out
    assert "todos:   0 next, 1 waiting" in out
