"""Durable, human-readable memory for a Papaya Agent Runtime instance.

Lives under ``.ppy/memory/`` (gitignored, machine-local) — the knowledge layer the
manager reads at the start of a session and updates as it learns, so it does not
relearn repositories, their relationships, or the user's preferences across
sessions. The authoritative *state* is ``.ppy/state.db``; these files are curated
notes on top of it.

Memory has **two explicit tiers**, split by who owns them:

- **Per-instance (this ``ppy``), spanning every repo — the manager's layer.** Top-level
  notes that apply across all managed repositories, including the manager's own work
  board::

      .ppy/memory/
        README.md          index of what lives here
        preferences.md     how the user likes things done (all repos)
        relationships.md   how the registered repos relate (cross-repo)
        tasks.md           the MANAGER's work board — what's delegated / in flight /
                           done across every repo
        improvements.md    aligned manager performance experiments and outcomes
        handoff.md         the last handoff snapshot — generated by `ppy handoff`,
                           named by the pickup prompt instead of carried in it

- **Per-repo, in addition — the shared worker workspace.** A directory per registered
  repository that workers read and update as they work, and the manager peeks at to
  follow progress without interrupting them::

        repos/<name>/
          notes.md         durable repo learnings (what it is, build/test/run,
                           conventions, gotchas) — workers consult and extend
          tasks.md         repo work + live progress log — workers record status
                           here so the manager can check in without asking

Everything here is plain Markdown so the manager and workers edit it directly. This
module owns only the canonical paths and the idempotent scaffolding/seeding — never a
schema.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from papaya_agent_runtime.paths import memory_dir

# --------------------------------------------------------------------------- #
# Tier 1 — per-instance (cross-repo)
# --------------------------------------------------------------------------- #


def index_path() -> Path:
    return memory_dir() / "README.md"


def preferences_path() -> Path:
    return memory_dir() / "preferences.md"


def relationships_path() -> Path:
    return memory_dir() / "relationships.md"


def board_path() -> Path:
    """The manager's cross-repo work board (`.ppy/memory/tasks.md`)."""
    return memory_dir() / "tasks.md"


def improvements_path() -> Path:
    """Curated history of aligned self-improvement commitments."""
    return memory_dir() / "improvements.md"


def handoff_path() -> Path:
    """The last handoff snapshot (`.ppy/memory/handoff.md`), generated by `ppy handoff`."""
    return memory_dir() / "handoff.md"


# --------------------------------------------------------------------------- #
# Tier 2 — per-repo
# --------------------------------------------------------------------------- #


def repos_root() -> Path:
    return memory_dir() / "repos"


def repo_dir(name: str) -> Path:
    return repos_root() / name


def repo_notes_path(name: str) -> Path:
    return repo_dir(name) / "notes.md"


def repo_tasks_path(name: str) -> Path:
    return repo_dir(name) / "tasks.md"


_INDEX = """\
# Papaya Agent Runtime memory

Machine-local, durable memory for this Papaya Agent Runtime instance (gitignored). The
manager reads this at the start of a session and updates it as it learns, so it does
not relearn repositories, their relationships, or your preferences.

Two tiers, split by who owns them:

**Per-instance (this `ppy`) — the manager's layer, spanning every repo.**
- `preferences.md` — how you like things done, across all repos.
- `relationships.md` — how the registered repositories relate.
- `tasks.md` — the manager's work board, *generated* by `ppy board` from the todo
  ledger + live task state (`ppy todo add|done|...` to change it; never hand-edit).
- `improvements.md` — aligned performance experiments and their outcomes.
- `handoff.md` — the last handoff snapshot (open work, ledger, known risks), *generated*
  by `ppy handoff`; the pickup prompt points here instead of carrying it. Never hand-edit.

**Per-repo — the shared worker workspace, under `repos/<name>/`.**
- `notes.md` — durable repo learnings (what it is, build/test/run, conventions,
  gotchas). Workers consult and extend it.
- `tasks.md` — repo work and a live progress log. Workers record status here as they
  go, so the manager can check in without interrupting them.

Authoritative lifecycle state (dispatched/running/blocked/done) is in `.ppy/state.db`
(surfaced via `ppy status`). These files are the human-readable layer on top: the
manager's board, durable learnings, and worker progress narrative.
"""

_PREFERENCES = """\
# Preferences (per-instance, all repos)

Durable, machine-local preferences the manager honors across every session and every
repository. Keep it short and current — prune anything stale. Repo-specific
conventions belong in that repo's `repos/<name>/notes.md`.

## Communication
- How updates should read (tone, length, how much detail to surface).

## Delivery & pull requests
- Branch naming, PR description style, reviewers, base branch, merge policy.

## Engineering defaults
- Languages, style, testing expectations, commands to always run.

## Standing decisions
- Durable global decisions (also recorded via `ppy answer --scope global`).
"""

_BOARD = """\
# Work board (manager)

Generated by `ppy board` from `.ppy/state.db` — do not hand-edit. Track intent with
`ppy todo add|done|block|unblock|drop`; task state comes from the lifecycle commands.
`ppy status` / `ppy handoff` read the same source. Run `ppy board --write` to refresh.

## In flight
- nothing running

## Blocked / needs me
- nothing waiting on me

## Next
- (no next steps recorded — `ppy todo add`)

## Done (recent)
- nothing yet
"""

_RELATIONSHIPS = """\
# Repository relationships (per-instance, cross-repo)

How the registered repositories relate, so cross-repo work isn't relearned each
time. This is the instance-wide map; repo-specific detail lives in each repo's
`repos/<name>/notes.md`.

## Dependencies
- `<repo-a>` depends on `<repo-b>` — why, and what breaks if out of order.

## Shared contracts
- APIs / schemas / packages shared across repos, and who owns them.

## Rollout order
- Preferred sequence for coordinated, cross-repo changes.
"""

_IMPROVEMENTS = """\
# Manager improvements

Curated, machine-local record of performance reviews the manager aligned with the
user. Detailed evidence and lifecycle state remain authoritative in `.ppy/state.db`.

## Aligned assessment history

Newest entries are appended below. The last aligned entry is the current plan unless
a later entry explicitly retires it.
"""


def _repo_notes_template(name: str, origin: str | None, default_branch: str | None) -> str:
    return f"""\
# {name} — notes

- Remote: {origin or "(unknown)"}
- Default branch: {default_branch or "(unknown)"}
- Registered: {date.today().isoformat()}

Durable, repo-specific notes so the manager doesn't relearn this repository each
session. Keep it concise and current.

## What it is
- One-paragraph purpose and high-level architecture.

## Build, test, run
- Exact commands: install, test, lint, run.

## Conventions & gotchas
- Style, patterns, landmines, review expectations specific to this repo.

## Key areas
- Important paths and entry points.

## Relationships
- Other repos it depends on or shares contracts with (mirror the cross-repo view in
  the instance-level `relationships.md`).
"""


def _repo_tasks_template(name: str) -> str:
    return f"""\
# {name} — follow-ups

Shared workspace for this repo. **Workers** add durable follow-ups here as they go; the
**manager** reads it when planning the next task. Live progress is *not* logged here —
workers report it with `ppy progress <task_id> --phase ... --note ...`, and
`ppy memory show --repo {name}` renders that log from state. Keep entries short.

## Now / next
- Things to pick up next in this repo.

## Backlog
- Nice-to-haves and deferred work.

## Known issues / tech debt
- Sharp edges to fix or route around.
"""


def worker_context(name: str, *, task_id: int | None = None, ends_at: str = "done") -> str:
    """A short preamble handed to a worker so it reports progress and uses repo memory.

    Uses absolute paths — a worker's cwd is its leased worktree, not the ``.ppy`` root.
    ``ppy`` is on the worker's PATH (see ``supervisor.runner.worker_env``).
    """
    notes = repo_notes_path(name)
    tasks = repo_tasks_path(name)
    tid = str(task_id) if task_id is not None else "<task_id>"
    from papaya_agent_runtime.environment import finish_instruction

    finish = finish_instruction(tid, ends_at)
    return (
        "Report progress with `ppy progress` (structured, visible to your manager):\n"
        f"- BEFORE you start implementing: `ppy progress {tid} --phase plan --note "
        '"<your intended approach in one or two sentences>"`. Your manager reviews the '
        "plan early and may steer you if the approach is off; a task that runs without a "
        "plan gets flagged.\n"
        f"- As you go: `ppy progress {tid} --phase implement|test|review --note "
        '"<what you did / what\'s next>"`; if you are stuck: `--phase blocked --note '
        '"<why>"`. Keep notes short. If a course-correction arrives, adjust and report it.\n'
        f"- BEFORE your final report, reflect: `ppy reflect {tid} --self "
        '"<what you learned; what went well or badly; what would have made this easier>" '
        '--manager "<how the brief, scope, steering, and review served you; what the '
        "manager should change>\"`. Be candid and specific — this is read in the manager's "
        "own performance review, and it is the only channel where your view counts.\n"
        f"- Then {finish}\n"
        "Shared repo memory (durable, and visible to your manager) — use it:\n"
        f"- Learnings: {notes}\n"
        "  Read it before you start; append any durable facts you discover "
        "(build/test commands, conventions, gotchas).\n"
        f"- Follow-ups: {tasks}\n"
        "  Durable backlog, tech debt, and known issues for this repo — add what you find; "
        "progress itself goes through `ppy progress`, not this file.\n"
        "Never write secrets or credentials into memory."
    )


def _write_if_absent(path: Path, content: str) -> None:
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def ensure_memory_layout() -> Path:
    """Create the memory tree and seed the per-instance notes if missing (idempotent)."""
    memory_dir().mkdir(parents=True, exist_ok=True)
    repos_root().mkdir(parents=True, exist_ok=True)
    _write_if_absent(index_path(), _INDEX)
    _write_if_absent(preferences_path(), _PREFERENCES)
    _write_if_absent(relationships_path(), _RELATIONSHIPS)
    _write_if_absent(board_path(), _BOARD)
    _write_if_absent(improvements_path(), _IMPROVEMENTS)
    return memory_dir()


def seed_repo_memory(
    name: str,
    *,
    origin: str | None = None,
    default_branch: str | None = None,
) -> Path:
    """Create the per-repo memory directory and its notes/tasks stubs (idempotent).

    Existing files are never overwritten — learnings the manager has already captured
    are preserved. Returns the repo's memory directory.
    """
    ensure_memory_layout()
    repo_dir(name).mkdir(parents=True, exist_ok=True)
    _write_if_absent(repo_notes_path(name), _repo_notes_template(name, origin, default_branch))
    _write_if_absent(repo_tasks_path(name), _repo_tasks_template(name))
    return repo_dir(name)
